apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim # Claim name
  labels:
    app: ghost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
spec:
  selector:
    matchLabels:
      app: ghost
  replicas: 2
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:1.24
        ports:
        - containerPort: 2368
        volumeMounts: # Mount a volume
        - name: ghost-persistent-storage
          mountPath: /var/lib/ghost/content # Mount path
      volumes: # Volume declaration
      - name: ghost-persistent-storage
        persistentVolumeClaim:
          claimName: ghost-pv-claim # Reference claim above
