apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: 30068 # Wordpress stores url in database. IF not fixed to original, it will redirect with 301.
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
#  type: NodePort
